export const clientes = [
  {
    nome: "Louie",
    idade: 30,
    email: "cliente1@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Myra",
    telefone: "(00) 1234-5678",
    cidade: "São Paulo",
    estado: "SP",
  },
  {
    nome: "Esta",
    idade: 25,
    email: "cliente2@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Annabel",
    telefone: "(00) 9876-5432",
    cidade: "Rio de Janeiro",
    estado: "RJ",
  },
  {
    nome: "Grayson",
    idade: 28,
    email: "cliente3@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Brody",
    telefone: "(00) 1111-2222",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    nome: "Jamir",
    idade: 30,
    email: "Roslyn1@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Sandy",
    telefone: "(00) 1234-5678",
    cidade: "São Paulo",
    estado: "SP",
  },
  {
    nome: "Ursula",
    idade: 25,
    email: "Oleta2@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Brett",
    telefone: "(00) 9876-5432",
    cidade: "Rio de Janeiro",
    estado: "RJ",
  },
  {
    nome: "Justine",
    idade: 28,
    email: "Humberto3@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Zoey",
    telefone: "(00) 1111-2222",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    nome: "Foster",
    idade: 35,
    email: "Horace4@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Arch",
    telefone: "(00) 3333-4444",
    cidade: "Brasília",
    estado: "DF",
  },
  {
    nome: "Nelson",
    idade: 40,
    email: "Joey5@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Larue",
    telefone: "(00) 5555-6666",
    cidade: "Salvador",
    estado: "BA",
  },
  {
    nome: "Autumn",
    idade: 22,
    email: "Leonel6@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Orrin",
    telefone: "(00) 7777-8888",
    cidade: "Fortaleza",
    estado: "CE",
  },
  {
    nome: "Roxane",
    idade: 27,
    email: "Roscoe7@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Braden",
    telefone: "(00) 9999-0000",
    cidade: "Porto Alegre",
    estado: "RS",
  },
  {
    nome: "Magnolia",
    idade: 31,
    email: "Rae8@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Vena",
    telefone: "(00) 1212-3434",
    cidade: "Curitiba",
    estado: "PR",
  },
  {
    nome: "Yolanda",
    idade: 29,
    email: "Laurel9@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Elsie",
    telefone: "(00) 2323-4545",
    cidade: "Recife",
    estado: "PE",
  },
  {
    nome: "Brandi",
    idade: 33,
    email: "Neal10@example.com",
    image: "https://dummyimage.com/300x300.png?text=Cliente%20Salvador",
    telefone: "(00) 5656-7878",
    cidade: "Manaus",
    estado: "AM",
  },
];
