export const databaseProducts = [
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 0,
    ref: 245343,
    name: "Camiseta Masculina",
    category: "Roupas",
    un: 4,
    purchase: "10,90",
    sale: "15,90",
    gain: "5,00",
    estoque: 100,
    stockMin: "10",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 1,
    ref: 134567,
    name: "Calça Jeans Feminina",
    category: "Roupas",
    un: 3,
    purchase: "49,90",
    sale: "69,90",
    gain: "20,00",
    estoque: 80,
    stockMin: "5",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 2,
    ref: 876543,
    name: "Tênis Esportivo",
    category: "Calçados",
    un: 2,
    purchase: "89,90",
    sale: "129,90",
    gain: "40,00",
    estoque: 120,
    stockMin: "8",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 3,
    ref: 987654,
    name: "Vestido de Festa",
    category: "Roupas",
    un: 5,
    purchase: "99,90",
    sale: "149,90",
    gain: "50,00",
    estoque: 60,
    stockMin: "3",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 4,
    ref: 543210,
    name: "Jaqueta de Couro",
    category: "Roupas",
    un: 1,
    purchase: "199,90",
    sale: "299,90",
    gain: "100,00",
    estoque: 30,
    stockMin: "2",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 5,
    ref: 123456,
    name: "Camisa Social Masculina",
    category: "Roupas",
    un: 7,
    purchase: "29,90",
    sale: "49,90",
    gain: "20,00",
    estoque: 90,
    stockMin: "6",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 6,
    ref: 789012,
    name: "Sapato Social Feminino",
    category: "Calçados",
    un: 4,
    purchase: "69,90",
    sale: "99,90",
    gain: "30,00",
    estoque: 75,
    stockMin: "5",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 7,
    ref: 345678,
    name: "Bolsa de Couro",
    category: "Acessórios",
    un: 2,
    purchase: "79,90",
    sale: "109,90",
    gain: "30,00",
    estoque: 50,
    stockMin: "4",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 8,
    ref: 901234,
    name: "Bermuda Masculina",
    category: "Roupas",
    un: 6,
    purchase: "19,90",
    sale: "29,90",
    gain: "10,00",
    estoque: 110,
    stockMin: "7",
    register: "Lojas Vest",
  },
  {
    photo: "https://dummyimage.com/300x300.png?text=Produto",
    ordem: 9,
    ref: 678901,
    name: "Sandália Feminina",
    category: "Calçados",
    un: 3,
    purchase: "39,90",
    sale: "59,90",
    gain: "20,00",
    estoque: 70,
    stockMin: "5",
    register: "Lojas Vest",
  },
  // Adicione mais objetos aqui, se necessário
];
